<a href="https://colab.research.google.com/github/ehBeak/animationProject/blob/main/testMask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

mask test

In [2]:
#library
import cv2 as cv
import os

os.getcwd()

'/content'

In [3]:
#video capture_com
vidcap = cv.VideoCapture('com.mp4')
success,image_bgr = vidcap.read()

count = 1
success = True

while success:
  success,image_bgr = vidcap.read()
  cv.imwrite("/content/imgcom/%d.png" % count, image_bgr)
  print("saved imagecom %d.png" % count)
  
  if cv.waitKey(10) == 27:                    
      break
  count += 1

saved imagecom 1.png
saved imagecom 2.png
saved imagecom 3.png
saved imagecom 4.png
saved imagecom 5.png
saved imagecom 6.png
saved imagecom 7.png
saved imagecom 8.png
saved imagecom 9.png
saved imagecom 10.png
saved imagecom 11.png
saved imagecom 12.png
saved imagecom 13.png
saved imagecom 14.png
saved imagecom 15.png
saved imagecom 16.png
saved imagecom 17.png
saved imagecom 18.png
saved imagecom 19.png
saved imagecom 20.png
saved imagecom 21.png
saved imagecom 22.png
saved imagecom 23.png
saved imagecom 24.png
saved imagecom 25.png
saved imagecom 26.png
saved imagecom 27.png
saved imagecom 28.png
saved imagecom 29.png
saved imagecom 30.png
saved imagecom 31.png
saved imagecom 32.png
saved imagecom 33.png
saved imagecom 34.png
saved imagecom 35.png
saved imagecom 36.png
saved imagecom 37.png
saved imagecom 38.png
saved imagecom 39.png
saved imagecom 40.png
saved imagecom 41.png
saved imagecom 42.png
saved imagecom 43.png
saved imagecom 44.png
saved imagecom 45.png
saved imagecom 46.p

error: ignored

In [4]:
# video capture_pha
vidcap = cv.VideoCapture('pha.mp4')
success,image_bgr = vidcap.read()

count = 1
success = True

while success:
  success,image_bgr = vidcap.read()
  cv.imwrite("/content/imgpha/%d.png" % count, image_bgr)
  print("saved imagepha %d.png" % count)
  
  if cv.waitKey(10) == 27:                    
      break
  count += 1

saved imagepha 1.png
saved imagepha 2.png
saved imagepha 3.png
saved imagepha 4.png
saved imagepha 5.png
saved imagepha 6.png
saved imagepha 7.png
saved imagepha 8.png
saved imagepha 9.png
saved imagepha 10.png
saved imagepha 11.png
saved imagepha 12.png
saved imagepha 13.png
saved imagepha 14.png
saved imagepha 15.png
saved imagepha 16.png
saved imagepha 17.png
saved imagepha 18.png
saved imagepha 19.png
saved imagepha 20.png
saved imagepha 21.png
saved imagepha 22.png
saved imagepha 23.png
saved imagepha 24.png
saved imagepha 25.png
saved imagepha 26.png
saved imagepha 27.png
saved imagepha 28.png
saved imagepha 29.png
saved imagepha 30.png
saved imagepha 31.png
saved imagepha 32.png
saved imagepha 33.png
saved imagepha 34.png
saved imagepha 35.png
saved imagepha 36.png
saved imagepha 37.png
saved imagepha 38.png
saved imagepha 39.png
saved imagepha 40.png
saved imagepha 41.png
saved imagepha 42.png
saved imagepha 43.png
saved imagepha 44.png
saved imagepha 45.png
saved imagepha 46.p

error: ignored

In [ ]:
# pha 이미지 shape : (w,h,c)
img = cv.imread('227.png', cv.IMREAD_UNCHANGED)
img.shape
print(img)


In [51]:
# pha 이미지 grayscale 확인 : 0과 255로 이루어진 것이 아님

test = cv.imread('70.png', cv.IMREAD_UNCHANGED)

# pha 이미지로 mask 만들기

masktest = np.zeros_like(test)

maskedtest = cv.bitwise_or(test, masktest)

os.getcwd()
cv.imwrite('maskedtest.png', maskedtest)


# BGR-> HSV -> rgb(200, 200, 200) 이상인 값 검은 색으로
maskedtest = cv.cvtColor(maskedtest, cv.COLOR_BGR2HSV)
maskedtestgray = cv.cvtColor(maskedtest, cv.COLOR_BGR2GRAY)


print(maskedtestgray)
maskedtestgray.shape

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... 39 42 53]
 [ 0  0  0 ... 38 42 55]
 [ 0  0  0 ... 39 42 56]]


(720, 1280)

In [39]:
# pha 이미지로 mask 만들기

import numpy as np

mask = np.zeros_like(img)

masked = cv.bitwise_or(img, mask)

os.getcwd()
cv.imwrite('masked.png', masked)



True

In [41]:
%cd ..
%cd imgpha

maskimg = cv.imread('masked.png', cv.IMREAD_UNCHANGED)

%cd ..
%cd imgcom

origin = cv.imread('227.png', cv.IMREAD_UNCHANGED)

masked = cv.bitwise_and(origin, maskimg)

os.getcwd()
cv.imwrite('masked.png', masked)

/content
/content/imgpha
/content
/content/imgcom


True

In [31]:
# 원래 mask의 크기
mask1 = np.zeros_like(img)
cv.circle(mask1, (260,210), 100, (255,255,255), -1)

masked1 = cv.bitwise_and(img, mask1)

In [ ]:
# 이미지 2차 처리
maskedImg = cv.imread('masked.png', cv.IMREAD_UNCHANGED)

